sudo: required

services:
  - docker

before_install: 
  - docker build -t hussnainjav3d/docker-startup -f Dockerfile.dev .

script:
  - docker run hussnainjav3d/docker-startup npm run test -- --coverage